### ISSUE TITLE
Неуместный IO

### ISSUE THREAD

**Issue by maked0n** [Sergmih/MyGame#2]
Для чего выводить где-то эту инфу? Если для отладки, то нужно и включить это только при отладке. Если в других целях, то это неподходящее место. https://github.com/Sergmih/MyGame/blob/d6471f1289b3a8a6d8c50de92b0adb68bce5dde5/Units.cpp#L10

**Comment by Sergmih** [comment]
Это было нужно пока писал код, просто забыл удалить. Сейчас убрал
