### ISSUE TITLE
Сборка в различных режимах

### ISSUE THREAD

**Issue by maked0n** [Sergmih/MyGame#4]
В требованиях написано:

> при вызове cmake && make должен собираться ваш проект в режиме Release
> при вызове cmake -DDEBUG=ON && make должен собираться ваш проект в режиме Debug
> при вызове cmake -DWITH_TEST=ON && make должен собираться ваш проект с тестами

я не увидел, чтобы это было реализовано

**Comment by Sergmih** [comment]
Вроде исправил
